### PR TITLE
Migrate website to Docusaurus 2

### PR DESCRIPTION
**Pull request by lex111**
Not everything has been done yet, but I already lingered a lot with migration, so I think I can show the first version of the website on v2.

Until I figured out Disqus, for some reason always the same comments showning up, although different identifiers and URLs are used :(

There are issues with dark theme (for example, for Disqus we need some CSS).

In general, there is some mess, some discrepancy, but I will be glad to any feedback!

Live demo: https://t-regx-test.now.sh/

Home

image

Docs

image

Blog

image

cc @yangshun, @endiliey, @Danon

### CODE REVIEW

**Comment by danon** [comment]
Wow, this looks really nice so fast :D 

Briefly looking at it, I can see Github star button doesn't work :D

**Comment by lex111** [comment]
The button in the header works for me, or do you mean the GH button in the footer? It is not there yet.

**Comment by danon** [comment]
@lex111 Oh yea, it does work now :| Must've been an error in my client.

And also I noticed that you changed `*italics*` in markdown to `_italics_`, but only in a few places. The rest remained `*italic*`. Is this by design? I mean, it renders all the same anyway, but still :D

**Comment by lex111** [comment]
@Danon Oops, this is apparently my VS Code did it :smiley:. I will revert these changes.

**Comment by danon** [comment]
I'm not really sure whether I need a dark theme. I could live without it :D It seems like a challenge designing all the colors and themes :D

**Comment by danon** [comment]
@lex111 Hey, sorry. I had to add another blog post today. Hope I didn't add any new work for you with migrating? :/

**Comment by lex111** [comment]
@Danon hi, no problem, of course :)
I will try to complete the migration soon!

**Comment by lex111** [comment]
Hmm, I just can’t figure it out with Disqus, so I get such a URL for get comments, what’s wrong with it?

https://disqus.com/embed/comments/?base=default&f=t-regx&t_i=%2Fblog%2F2019%2F07%2F01%2Fcrazy-stargazers&t_u=http%3A%2F%2Flocalhost%3A3000%2Fblog%2F2019%2F07%2F01%2Fcrazy-stargazers&t_e=%5C%22The%20best%20Stargazers!%5C%22%20Reloaded&t_d=%22The%20best%20Stargazers!%22%20Reloaded&t_t=%5C%22The%20best%20Stargazers!%5C%22%20Reloaded&s_o=default

**Comment by danon** [comment]
@lex111 Are you talking about the same comment section displaying on multiple sections? It was by design, I wanted the same comment sections on multiple sections.

**Comment by danon** [comment]
@lex111 Just a question. Will Docusaurus 2 have support for meta tags?

**Comment by lex111** [comment]
@Danon the same comments for all pages, I get that, but should there be own comments for each post, right? This is what I can’t achieve now.

> Will Docusaurus 2 have support for meta tags?

Do you mean this? https://v2.docusaurus.io/docs/markdown-features/#markdown-headers

**Comment by danon** [comment]
> I get that, but should there be own comments for each post, right? This is what I can’t achieve now.

Would you like to contact me on discord? I'm sure I can help

> Do you mean this? https://v2.docusaurus.io/docs/markdown-features/#markdown-headers

Yes, exactly. Thanks.

**Comment by lex111** [comment]
> Would you like to contact me on discord? I'm sure I can help

I did not find you, so here is my ID - lex111#3098.

**Comment by lex111** [comment]
@Danon In general, I updated the website to the latest version (.32), I still did not solve the problem with comments, but maybe you can do it later (after migration)? It will be easier on your part, now comments have been added to Blog, it remains to understand why they are the same for all pages.

**Comment by danon** [comment]
> @Danon In general, I updated the website to the latest version (.32), 

Sweet thanks!
> I still did not solve the problem with comments, but maybe you can do it later (after migration)? It will be easier on your part, 

Sure :)
> now comments have been added to Blog, it remains to understand why they are the same for all pages

I can't see comments on blog? :/


PS: So what's next with the migration? :)

**Comment by lex111** [comment]
> I can't see comments on blog? :/


Try again - https://t-regx-test.now.sh/blog/2019/10/15/dont-forget-about-t-regx

> PS: So what's next with the migration? :)

If there are no more critical issues, then I think we can merge the PR.

**Comment by danon** [comment]
Could you please, do the followings:
 - Disable the dark theme switcher for now?
 - Hide `box-shadow` on `nav.navbar`? I don't really like it

And my last question. Is there a way I can add my own code coloring for highlights? Like my custom highlighting rules?

**Comment by danon** [comment]
Could you also remove underline decoration on anchor link hover in docs?
image

**Comment by lex111** [comment]
> Disable the dark theme switcher for now?

Don't you like dark mode?

**Comment by danon** [comment]
I expect I would probably have to spend sometime adjusting the darktheme, because, somehow I feel like it's a bit 1990-2000 look in this dark mode. I could fix it probably, style it a little bit better, but my main focus is on the library now, not on the webpage.

So I thought about switching it off for now, and adding the option later, when the dark theme looks more modern

**Comment by danon** [comment]
image

These colors are all off :/

**Comment by endiliey** [comment]
We might need to add an option “themeConfig.disableDarkMode” on docusaurus side to disable dark mode toggle. Theres no way to disable it now without swizzling

**Comment by lex111** [comment]
@Danon done :heavy_check_mark:  -> https://t-regx-test.now.sh/

> Is there a way I can add my own code coloring for highlights? Like my custom highlighting rules?

Yes, you can [specify the path](https://github.com/lex111/T-Regx.github.io/blob/77856b0e927c7cbd85c0227327d953c9dddb8c04/website/docusaurus.config.js#L42) to your theme. You can take [any existing theme](https://github.com/FormidableLabs/prism-react-renderer/tree/master/src/themes) as a basis and change its colors.

**Comment by lex111** [comment]
In addition to the question of specifying your own theme for Prism - do we need to add the ability for end-user to specify an another Prism theme in dark mode?

**Comment by danon** [comment]
I'm not sure about your added file `custom.css`, while I have `custom.scss` file

**Comment by danon** [comment]
but it's all right, I'll do it: )

**Comment by lex111** [comment]
In fact, `custom.scss` will no longer work, because v2 does not support SASS out of the box. And then, many styles became irrelevant. In general, `custom.css` contains all the styles that were before.

**Comment by yangshun** [comment]
@Danon how is it going? Let us know if you need help :)

**Comment by danon** [comment]
I'm trying to comprehend just in my head what really got changed, and cope with the fact that the page still looks a bit different than before.

Thanks for great effort @lex111! I'll deploy your new page on wednesday night, ok? :)

**Comment by danon** [comment]
@lex111 @yangshun @endiliey Thank you very much for your help :D I've merge the PR, T-Regx now officially runs on docusaurus 2.0 :) Thank you again :> Very much enjoyed working with docusaurus team.

**Comment by yangshun** [comment]
Welcome, do you intend to make the website live? 😄

**Comment by danon** [comment]
@yangshun Deployed :>

**Comment by yangshun** [comment]
Looks awesome! Thanks @lex111 and @Danon!

**Pull request merged**
